module.exports = {
    AttendanceDaily: require('./attendanceDaily.model'),
    AttendanceLog: require('./attendanceLog.model'),
    AttendanceMachine: require('./attendanceMachine.model'),
    AttendanceRequest: require('./attendanceRequest.model'),
    AttendanceSummary: require('./attendanceSummary.model'),
    CompanyAsset: require('./companyAsset.model'),
    Department: require('./department.model'),
    Designation: require('./designation.model'),
    Employee: require('./employee.model'),
    EmployeeDocument: require('./employeeDocument.model'),
    ExpenseClaim: require('./expenseClaim.model'),
    Feedback: require('./feedback.model'),
    GeoFencing: require('./geoFencing.model'),
    Goal: require('./goal.model'),
    Holiday: require('./holiday.model'),
    LeaveBalance: require('./leaveBalance.model'),
    LeaveRequest: require('./leaveRequest.model'),
    LeaveTransaction: require('./leaveTransaction.model'),
    Payslip: require('./payslip.model'),
    ReviewCycle: require('./reviewCycle.model'),
    SalaryStructure: require('./salaryStructure.model'),
    Shift: require('./shift.model'),
    ShiftAssignment: require('./shiftAssignment.model'),
    ShiftGroup: require('./shiftGroup.model'),
    TaxDeduction: require('./taxDeduction.model')
};
