version: '3.8'

services:
  api:
    build: .
    command: npm run dev
    ports:
      - '4000:4000'
    env_file: .env
    environment:
      MONGO_URI: mongodb://mongo:27017
      REDIS_URL: redis://redis:6379
      REDIS_HOST: redis
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
      - redis

  worker-products:
    build: .
    command: npm run worker:products
    env_file: .env
    environment:
      MONGO_URI: mongodb://mongo:27017
      REDIS_URL: redis://redis:6379
      REDIS_HOST: redis
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:7
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
