const express = require('express');
const router = express.Router();
const multer = require('multer');
const upload = multer({ storage: multer.memoryStorage() });

const channelCtrl = require('../../modules/organization/core/channel.controller');
const messageCtrl = require('../../modules/notification/core/message.controller');
const authController = require('../../modules/auth/core/auth.controller');
const { checkPermission } = require('../../core/middleware/permission.middleware');
const { PERMISSIONS } = require('../../config/permissions');
router.use(authController.protect);
router.get('/channels', checkPermission(PERMISSIONS.CHAT.READ), channelCtrl.listChannels);
router.post('/channels', checkPermission(PERMISSIONS.CHAT.MANAGE_CHANNEL), channelCtrl.createChannel);
router.post('/messages', checkPermission(PERMISSIONS.CHAT.SEND), messageCtrl.sendMessage);
router.post('/upload', checkPermission(PERMISSIONS.CHAT.SEND), upload.single('file'), messageCtrl.uploadAttachment);
router.get('/channels/:channelId/messages', checkPermission(PERMISSIONS.CHAT.READ), messageCtrl.getMessages);
router.post('/channels/:channelId/members', checkPermission(PERMISSIONS.CHAT.MANAGE_CHANNEL), channelCtrl.addMember);
router.delete('/channels/:channelId/members/:userId', checkPermission(PERMISSIONS.CHAT.MANAGE_CHANNEL), channelCtrl.removeMember);
router.post('/channels/:channelId/leave', checkPermission(PERMISSIONS.CHAT.READ), channelCtrl.leaveChannel);
router.patch('/channels/:channelId/disable', checkPermission(PERMISSIONS.CHAT.MANAGE_CHANNEL), channelCtrl.disableChannel);
router.patch('/channels/:channelId/enable', checkPermission(PERMISSIONS.CHAT.MANAGE_CHANNEL), channelCtrl.enableChannel);
router.patch('/messages/:messageId', checkPermission(PERMISSIONS.CHAT.SEND), messageCtrl.editMessage);
router.delete('/messages/:messageId', checkPermission(PERMISSIONS.CHAT.DELETE), messageCtrl.deleteMessage);
router.patch('/messages/:messageId/read', checkPermission(PERMISSIONS.CHAT.READ), messageCtrl.markMessageAsRead);
module.exports = router;