// src/models/storefront/storefrontPage.model.js
const mongoose = require('mongoose');

// Sub-schema for individual sections (Hero, Product Grid, etc.)
const sectionSchema = new mongoose.Schema({
  id: { type: String, required: true }, 
  type: { type: String, required: true }, // e.g. 'hero_banner'
  
  position: { type: Number, required: true },
  
  // The content configuration
  config: { type: mongoose.Schema.Types.Mixed, default: {} },
  
  // Data Source logic
  dataSource: { 
    type: String, 
    enum: ['static', 'smart', 'manual', 'dynamic', 'category'], 
    default: 'static' 
  },
  
  // Link to dynamic data
  smartRuleId: { type: mongoose.Schema.Types.ObjectId, ref: 'SmartRule' },
  manualData: { 
    productIds: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Product' }],
    categoryIds: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Master' }]
  },

  isActive: { type: Boolean, default: true }
}, { _id: false });

const pageSchema = new mongoose.Schema({
  organizationId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Organization',
    required: true,
    index: true
  },

  name: { type: String, required: true, trim: true, maxlength: 100 },
  slug: { 
    type: String, 
    required: true, 
    lowercase: true,
    trim: true,
    match: [/^[a-z0-9-/]+$/, 'Invalid slug format']
  },

  pageType: {
    type: String,
    enum: ['home', 'product', 'category', 'blog', 'content', 'policy', 'system'],
    default: 'content'
  },

  sections: [sectionSchema],

  // SEO settings
  seo: {
    title: String,
    description: String,
    keywords: [String],
    ogImage: String,
    noIndex: { type: Boolean, default: false }
  },

  // Theme Override: A specific page can look different (e.g., 'theme-dark' for Black Friday)
  pageThemeId: { type: String }, 

  status: { type: String, enum: ['draft', 'published', 'archived'], default: 'draft', index: true },
  isPublished: { type: Boolean, default: false },
  publishedAt: { type: Date },

  // System Flags
  isHomepage: { type: Boolean, default: false },
  isSystemPage: { type: Boolean, default: false }, // If true, cannot be deleted
  
  // Soft Delete for safety
  isDeleted: { type: Boolean, default: false, index: true },

  viewCount: { type: Number, default: 0 }

}, { timestamps: true });

pageSchema.index({ organizationId: 1, slug: 1 }, { unique: true });
pageSchema.index({ organizationId: 1, isHomepage: 1 });

module.exports = mongoose.model('StorefrontPage', pageSchema);


// // src/models/storefront/storefrontPage.model.js
// const mongoose = require('mongoose');

// // Sub-schema for individual sections (Hero, Product Grid, etc.)
// const sectionSchema = new mongoose.Schema({
//   id: { type: String, required: true }, // generated by nanoid
//   type: { type: String, required: true }, // e.g. 'hero_banner', 'product_grid'
  
//   position: { type: Number, required: true },
  
//   // The content configuration (Text, Images, specific overrides)
//   config: { type: mongoose.Schema.Types.Mixed, default: {} },
  
//   // Data Source logic
//   dataSource: { 
//     type: String, 
//     enum: ['static', 'smart', 'manual', 'dynamic', 'category'], 
//     default: 'static' 
//   },
  
//   // Link to dynamic data
//   smartRuleId: { type: mongoose.Schema.Types.ObjectId, ref: 'SmartRule' },
//   manualData: { 
//     productIds: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Product' }],
//     categoryIds: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Master' }]
//   },

//   isActive: { type: Boolean, default: true }
// }, { _id: false });

// const pageSchema = new mongoose.Schema({
//   organizationId: {
//     type: mongoose.Schema.Types.ObjectId,
//     ref: 'Organization',
//     required: true,
//     index: true
//   },

//   name: { type: String, required: true, trim: true, maxlength: 100 },
//   slug: { 
//     type: String, 
//     required: true, 
//     lowercase: true,
//     trim: true,
//     match: [/^[a-z0-9-/]+$/, 'Invalid slug format']
//   },

//   pageType: {
//     type: String,
//     enum: ['home', 'product', 'category', 'blog', 'content', 'policy', 'system'],
//     default: 'content'
//   },

//   sections: [sectionSchema],

//   // SEO settings
//   seo: {
//     title: String,
//     description: String,
//     keywords: [String],
//     ogImage: String,
//     noIndex: { type: Boolean, default: false }
//   },

//   // Theme Override for specific pages (e.g., a dark landing page on a light site)
//   // If null, uses Global Layout theme
//   pageThemeId: { type: String }, // e.g., 'theme-dark'

//   status: { type: String, enum: ['draft', 'published', 'archived'], default: 'draft', index: true },
//   isPublished: { type: Boolean, default: false },
//   isHomepage: { type: Boolean, default: false },
  
//   viewCount: { type: Number, default: 0 }

// }, { timestamps: true });

// pageSchema.index({ organizationId: 1, slug: 1 }, { unique: true });
// pageSchema.index({ organizationId: 1, isHomepage: 1 });

// module.exports = mongoose.model('StorefrontPage', pageSchema);

// // // src/models/storefront/storefrontPage.model.js
// // const mongoose = require('mongoose');

// // const sectionSchema = new mongoose.Schema({
// //   id: { type: String, required: true },
// //   type: { type: String, required: true },
  
// //   // Controls visual layout order
// //   position: { type: Number, required: true },
  
// //   // The actual content/settings
// //   config: { type: mongoose.Schema.Types.Mixed, default: {} },
  
// //   // Data Fetching Logic
// //   dataSource: { 
// //     type: String, 
// //     enum: ['static', 'smart', 'manual', 'dynamic', 'category'], 
// //     default: 'static' 
// //   },
  
// //   // If 'smart', link to a rule
// //   smartRuleId: { type: mongoose.Schema.Types.ObjectId, ref: 'SmartRule' },
  
// //   // If 'manual', store IDs
// //   manualData: { 
// //     productIds: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Product' }],
// //     categoryIds: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Master' }]
// //   },

// //   isActive: { type: Boolean, default: true }
// // }, { _id: false });

// // const pageSchema = new mongoose.Schema({
// //   organizationId: {
// //     type: mongoose.Schema.Types.ObjectId,
// //     ref: 'Organization',
// //     required: true,
// //     index: true
// //   },

// //   // Identity
// //   name: { type: String, required: true, trim: true, maxlength: 100 },
// //   slug: { 
// //     type: String, 
// //     required: true, 
// //     trim: true, 
// //     lowercase: true,
// //     match: [/^[a-z0-9-/]+$/, 'Slug can only contain lowercase letters, numbers, and hyphens']
// //   },

// //   pageType: {
// //     type: String,
// //     enum: ['home', 'product', 'category', 'content', 'blog', 'policy', 'custom', 'system'],
// //     default: 'custom'
// //   },

// //   // Content
// //   sections: [sectionSchema],

// //   // SEO & Social Sharing
// //   seo: {
// //     title: { type: String, trim: true, maxlength: 70 },
// //     description: { type: String, trim: true, maxlength: 160 },
// //     keywords: [{ type: String }],
// //     ogImage: { type: String }, // Share image URL
// //     noIndex: { type: Boolean, default: false }
// //   },

// //   // Advanced: Per-page scripts (e.g., Landing page specific conversion pixel)
// //   scripts: {
// //     head: { type: String }, // <script>...</script>
// //     body: { type: String }
// //   },

// //   // Status
// //   status: { type: String, enum: ['draft', 'published', 'archived'], default: 'draft', index: true },
// //   isPublished: { type: Boolean, default: false },
// //   publishedAt: { type: Date },

// //   // System Flags
// //   isHomepage: { type: Boolean, default: false },
// //   isSystemPage: { type: Boolean, default: false }, // If true, cannot be deleted (e.g. 404 page, cart)
// //   isDeleted: { type: Boolean, default: false }, // Soft Delete flag

// //   // Analytics
// //   viewCount: { type: Number, default: 0 }

// // }, { timestamps: true });

// // // Compound Indexes for Speed
// // pageSchema.index({ organizationId: 1, slug: 1 }, { unique: true });
// // pageSchema.index({ organizationId: 1, isHomepage: 1 });

// // module.exports = mongoose.model('StorefrontPage', pageSchema);

// // // const mongoose = require('mongoose');
// // // const { nanoid } = require('nanoid');

// // // const sectionSchema = new mongoose.Schema({
// // //   id: {
// // //     type: String,
// // //     default: () => nanoid(8),
// // //     required: true
// // //   },
  
// // //   // ✅ UPDATED: Complete List of "Best UI" Sections
// // //   type: {
// // //     type: String,
// // //     required: [true, 'Section type is required'],
// // //     trim: true,
// // //     enum: [
// // //       // Hero
// // //       'hero_banner', 'video_hero', 
      
// // //       // Products
// // //       'product_slider', 'product_grid', 'featured_product',
      
// // //       // Content & Layout
// // //       'feature_grid', 'category_grid', 'text_content', 'split_image_text',
      
// // //       // Trust & Social
// // //       'testimonial_slider', 'logo_cloud', 'instagram_feed', 'stats_counter',
      
// // //       // Marketing & Utility
// // //       'newsletter_signup', 'countdown_timer', 'faq_accordion', 'pricing_table', 'cta_banner',
      
// // //       // Contact & Misc
// // //       'contact_form', 'map_locations', 'blog_feed', 'image_gallery', 'social_proof'
// // //     ]
// // //   },
  
// // //   position: {
// // //     type: Number,
// // //     required: true,
// // //     min: 0
// // //   },
  
// // //   config: {
// // //     type: mongoose.Schema.Types.Mixed,
// // //     required: true,
// // //     default: {}
// // //   },
  
// // //   // Data Source Configuration
// // //   dataSource: {
// // //     type: String,
// // //     enum: ['static', 'smart', 'manual', 'dynamic', 'category'],
// // //     default: 'static'
// // //   },
  
// // //   // For Smart Rules (Best Sellers, etc.)
// // //   smartRuleId: {
// // //     type: mongoose.Schema.Types.ObjectId,
// // //     ref: 'SmartRule'
// // //   },
  
// // //   // For Manual Product Selection
// // //   manualData: {
// // //     type: mongoose.Schema.Types.Mixed 
// // //     // Structure: { productIds: [ObjectId], categoryIds: [ObjectId] }
// // //   },
  
// // //   isActive: {
// // //     type: Boolean,
// // //     default: true
// // //   }
// // // }, { _id: false });

// // // const pageSchema = new mongoose.Schema({
// // //   // --- 1. CORE IDENTITY ---
// // //   organizationId: {
// // //     type: mongoose.Schema.Types.ObjectId,
// // //     ref: 'Organization',
// // //     required: [true, 'Organization ID is required'],
// // //     index: true
// // //   },

// // //   name: {
// // //     type: String,
// // //     required: [true, 'Page name is required'],
// // //     trim: true,
// // //     maxlength: [100, 'Page name cannot exceed 100 characters']
// // //   },
  
// // //   slug: {
// // //     type: String,
// // //     required: [true, 'Page slug is required'],
// // //     trim: true,
// // //     lowercase: true,
// // //     match: [/^[a-z0-9-]+$/, 'Slug can only contain lowercase letters, numbers, and hyphens']
// // //   },
  
// // //   pageType: {
// // //     type: String,
// // //     required: true,
// // //     enum: ['home', 'products', 'product_detail', 'category', 'blog', 'about', 'contact', 'landing', 'custom'],
// // //     default: 'custom'
// // //   },

// // //   // --- 2. CONTENT ---
// // //   sections: [sectionSchema],

// // //   // --- 3. SEO & SOCIAL ---
// // //   seo: {
// // //     title: { type: String, trim: true, maxlength: 60 },
// // //     description: { type: String, trim: true, maxlength: 160 },
// // //     keywords: [{ type: String, trim: true }],
// // //     ogImage: { type: String, trim: true }, // Social Share Image
// // //     canonicalUrl: { type: String, trim: true },
// // //     noIndex: { type: Boolean, default: false }
// // //   },

// // //   // --- 4. PAGE-SPECIFIC THEME OVERRIDES ---
// // //   // (Optional: Allows a "Black Friday" page to look different from the main site)
// // //   theme: {
// // //     primaryColor: { type: String, match: [/^#[0-9A-Fa-f]{6}$/, 'Invalid hex color'] },
// // //     secondaryColor: { type: String, match: [/^#[0-9A-Fa-f]{6}$/, 'Invalid hex color'] },
// // //     backgroundColor: { type: String, default: '#FDFCF8' }, // Page Background
// // //     fontFamily: { type: String },
// // //     borderRadius: { type: String, enum: ['none', 'sm', 'md', 'lg', 'xl'] }
// // //   },

// // //   // --- 5. PUBLISHING ---
// // //   status: {
// // //     type: String,
// // //     enum: ['draft', 'published', 'archived'],
// // //     default: 'draft',
// // //     index: true
// // //   },
// // //   isPublished: { type: Boolean, default: false, index: true },
// // //   publishedAt: { type: Date },
  
// // //   isHomepage: { type: Boolean, default: false },

// // //   // --- 6. METADATA ---
// // //   version: { type: Number, default: 1 },
// // //   viewCount: { type: Number, default: 0 },
// // //   lastViewedAt: { type: Date },
  
// // //   createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' }

// // // }, {
// // //   timestamps: true,
// // //   toJSON: { virtuals: true },
// // //   toObject: { virtuals: true }
// // // });

// // // // Indexes
// // // pageSchema.index({ organizationId: 1, slug: 1 }, { unique: true });
// // // pageSchema.index({ organizationId: 1, isHomepage: 1 });

// // // // Ensure only one Homepage per Org
// // // pageSchema.pre('save', async function (next) {
// // //   if (this.isHomepage && (this.isNew || this.isModified('isHomepage'))) {
// // //     try {
// // //       await this.constructor.updateMany(
// // //         { organizationId: this.organizationId, _id: { $ne: this._id } },
// // //         { $set: { isHomepage: false } }
// // //       );
// // //     } catch (error) {
// // //       return next(error);
// // //     }
// // //   }
  
// // //   // Auto SEO Fallback
// // //   if (!this.seo.title && this.name) {
// // //     this.seo.title = this.name;
// // //   }
  
// // //   next();
// // // });

// // // module.exports = mongoose.model('StorefrontPage', pageSchema);
