module.exports = {
  // --- Core API v1 ---
  authRoutes: require('./routes/v1/auth.routes.js'),
  userRoutes: require('./routes/v1/user.routes.js'),
  roleRoutes: require('./routes/v1/roles.routes.js'),
  organizationRoutes: require('./routes/v1/organization.routes.js'),
  organizationExtrasRoutes: require('./routes/v1/organizationExtras.routes.js'),
  branchRoutes: require('./routes/v1/branch.routes.js'),
  productRoutes: require('./routes/v1/product.routes.js'),
  customerRoutes: require('./routes/v1/customer.routes.js'),
  supplierRoutes: require('./routes/v1/supplier.routes.js'),
  dropdownRoutes: require('./modules/master/core/dropdownlist'),

  // --- Transactions & Finance ---
  invoiceRoutes: require('./routes/v1/invoice.routes.js'),
  invoicePDFRoutes: require('./routes/v1/invoicePDF.routes.js'),
  paymentRoutes: require('./routes/v1/payment.routes.js'),
  salesRoutes: require('./routes/v1/sales.routes.js'),
  purchaseRoutes: require('./routes/v1/purchase.routes.js'),
  emiRoutes: require('./routes/v1/emi.routes.js'),
  transactionRoutes: require('./routes/v1/transaction.routes.js'),
  partyTransactionRoutes: require('./routes/v1/partyTransaction.routes.js'),
  ledgersRoutes: require('./routes/v1/ledger.routes.js'),
  statementsRoutes: require('./routes/v1/statements.routes.js'),
  accountRoutes: require('./routes/v1/account.routes.js'),
  reconciliationRoutes: require('./routes/v1/reconciliation.routes.js'),

  // --- Inventory & Logistics ---
  inventoryRoutes: require('./routes/v1/inventory.routes.js'),
  stockRoutes: require('./routes/v1/stock.routes.js'),
  assetsRoutes: require('./routes/v1/asset.routes.js'),

  // --- Analytics & Admin ---
  dashboard: require('./routes/v1/dashboard.routes.js'),
  analyticsRoutes: require('./routes/v1/analytics.routes.js'),
  chartRoutes: require('./routes/v1/chart.routes.js'),
  adminRouter: require('./routes/v1/admin.routes.js'),
  customerAnalytics: require('./routes/v1/customer.analytics.routes.js'),
  logRoutes: require('./routes/v1/log.routes.js'),

  // --- Communication & AI ---
  notificationRoutes: require('./routes/v1/notification.routes.js'),
  noteRoutes: require('./routes/v1/note.routes.js'),
  chatRoutes: require('./routes/v1/chat.routes.js'),
  aiAgent: require('./routes/v1/aiAgent.routes.js'),
  announcementRoutes: require('./routes/v1/announcement.routes.js'),
  feedRoutes: require('./routes/v1/feed.routes.js'),

  // --- System & Master Data ---
  searchRoutes: require('./routes/v1/search.routes.js'),
  masterRoutes: require('./routes/v1/master.routes.js'),
  masterListRoutes: require('./routes/v1/masterList.routes.js'),
  masterTypeRoutes: require('./routes/v1/masterType.routes.js'),
  sessionRoutes: require('./routes/v1/session.routes.js'),
  ownershipRoutes: require('./routes/v1/ownership.routes.js'),
  automationRoutes: require('./routes/v1/automation.routes.js'),
  cronRoutes: require('./routes/v1/cron.routes.js'),

  // --- External/Public Modules ---
  hrmsRoutes: require('./modules/HRMS/routes/index'),
  storefrontPublicRoutes: require('./PublicModules/routes/storefront/public.routes.js'),
  storefrontAdminRoutes: require('./PublicModules/routes/storefront/admin.routes.js'),
  smartRuleRoutes: require('./PublicModules/routes/storefront/smartRule.routes.js'),
};

// module.exports = {
//   // Core V1
//   authRoutes: require('./v1/auth.routes.js'),
//   userRoutes: require('./v1/user.routes.js'),
//   roleRoutes: require('./v1/roles.routes.js'),
//   organizationRoutes: require('./v1/organization.routes.js'),
//   organizationExtrasRoutes: require('./v1/organizationExtras.routes.js'),
//   branchRoutes: require('./v1/branch.routes.js'),
//   productRoutes: require('./v1/product.routes.js'),
//   customerRoutes: require('./v1/customer.routes.js'),
//   supplierRoutes: require('./v1/supplier.routes.js'),
//   dropdownRoutes: require('../modules/master/core/dropdownlist'), // Note the path

//   // Billing & Finance
//   invoiceRoutes: require('./v1/invoice.routes.js'),
//   invoicePDFRoutes: require('./v1/invoicePDF.routes.js'),
//   paymentRoutes: require('./v1/payment.routes.js'),
//   salesRoutes: require('./v1/sales.routes.js'),
//   purchaseRoutes: require('./v1/purchase.routes.js'),
//   emiRoutes: require('./v1/emi.routes.js'),
//   transactionRoutes: require('./v1/transaction.routes.js'),
//   partyTransactionRoutes: require('./v1/partyTransaction.routes.js'),
//   ledgersRoutes: require('./v1/ledger.routes.js'),
//   statementsRoutes: require('./v1/statements.routes.js'),
//   accountRoutes: require('./v1/account.routes.js'),

//   // Analytics & Dashboards
//   dashboardRoutes: require('./v1/dashboard.routes.js'),
//   analyticsRoutes: require('./v1/analytics.routes.js'),
//   chartRoutes: require('./v1/chart.routes.js'),
//   adminRoutes: require('./v1/admin.routes.js'),
//   customerAnalytics: require('./v1/customer.analytics.routes.js'),

//   // HRMS & Modules
//   hrmsMain: require('../modules/HRMS/routes/index'),

//   // Utilities
//   notificationRoutes: require('./v1/notification.routes.js'),
//   noteRoutes: require('./v1/note.routes.js'),
//   chatRoutes: require('./v1/chat.routes.js'),
//   aiAgent: require('./v1/aiAgent.routes.js'),
//   searchRoutes: require('./v1/search.routes.js'),
//   announcementRoutes: require('./v1/announcement.routes.js'),
//   masterRoutes: require('./v1/master.routes.js'),
//   masterListRoutes: require('./v1/masterList.routes.js'),
//   masterTypeRoutes: require('./v1/masterType.routes.js'),
//   logRoutes: require('./v1/log.routes.js'),
//   sessionRoutes: require('./v1/session.routes.js'),
//   ownershipRoutes: require('./v1/ownership.routes.js'),
//   inventoryRoutes: require('./v1/inventory.routes.js'),
//   feedRoutes: require('./v1/feed.routes.js'),
//   reconciliationRoutes: require('./v1/reconciliation.routes.js'),
//   automationRoutes: require('./v1/automation.routes.js'),
//   assetRoutes: require('./v1/asset.routes.js'),
//   stockRoutes: require('./v1/stock.routes.js'),
//   cronRoutes: require('./v1/cron.routes.js'),

//   // Storefront (Public Modules)
//   storefrontPublic: require('../PublicModules/routes/storefront/public.routes.js'),
//   storefrontAdmin: require('../PublicModules/routes/storefront/admin.routes.js'),
//   smartRuleRoutes: require('../PublicModules/routes/storefront/smartRule.routes.js'),
// };

// // module.exports = {
// //   // --- V1 Routes (Main API) ---
// //   accountRoutes: require('./routes/v1/account.routes.js'),
// //   adminRoutes: require('./routes/v1/admin.routes.js'),
// //   aiAgentRoutes: require('./routes/v1/aiAgent.routes.js'),
// //   analyticsRoutes: require('./routes/v1/analytics.routes.js'),
// //   announcementRoutes: require('./routes/v1/announcement.routes.js'),
// //   assetRoutes: require('./routes/v1/asset.routes.js'),
// //   authRoutes: require('./routes/v1/auth.routes.js'),
// //   automationRoutes: require('./routes/v1/automation.routes.js'),
// //   branchRoutes: require('./routes/v1/branch.routes.js'),
// //   chartRoutes: require('./routes/v1/chart.routes.js'),
// //   chatRoutes: require('./routes/v1/chat.routes.js'),
// //   cronRoutes: require('./routes/v1/cron.routes.js'),
// //   customerAnalyticsRoutes: require('./routes/v1/customer.analytics.routes.js'),
// //   customerRoutes: require('./routes/v1/customer.routes.js'),
// //   dashboardRoutes: require('./routes/v1/dashboard.routes.js'),
// //   emiRoutes: require('./routes/v1/emi.routes.js'),
// //   feedRoutes: require('./routes/v1/feed.routes.js'),
// //   inventoryRoutes: require('./routes/v1/inventory.routes.js'),
// //   invoicePdfRoutes: require('./routes/v1/invoicePDF.routes.js'),
// //   invoiceRoutes: require('./routes/v1/invoice.routes.js'),
// //   ledgerRoutes: require('./routes/v1/ledger.routes.js'),
// //   logRoutes: require('./routes/v1/log.routes.js'),
// //   masterListRoutes: require('./routes/v1/masterList.routes.js'),
// //   masterRoutes: require('./routes/v1/master.routes.js'),
// //   masterTypeRoutes: require('./routes/v1/masterType.routes.js'),
// //   noteRoutes: require('./routes/v1/note.routes.js'),
// //   notificationRoutes: require('./routes/v1/notification.routes.js'),
// //   organizationExtrasRoutes: require('./routes/v1/organizationExtras.routes.js'),
// //   organizationRoutes: require('./routes/v1/organization.routes.js'),
// //   ownershipRoutes: require('./routes/v1/ownership.routes.js'),
// //   partyTransactionRoutes: require('./routes/v1/partyTransaction.routes.js'),
// //   paymentRoutes: require('./routes/v1/payment.routes.js'),
// //   productRoutes: require('./routes/v1/product.routes.js'),
// //   purchaseRoutes: require('./routes/v1/purchase.routes.js'),
// //   reconciliationRoutes: require('./routes/v1/reconciliation.routes.js'),
// //   rolesRoutes: require('./routes/v1/roles.routes.js'),
// //   salesReturnRoutes: require('./routes/v1/salesReturn.routes.js'),
// //   salesRoutes: require('./routes/v1/sales.routes.js'),
// //   searchRoutes: require('./routes/v1/search.routes.js'),
// //   sessionRoutes: require('./routes/v1/session.routes.js'),
// //   shiftRoutes: require('./routes/v1/shift.routes.js'),
// //   statementsRoutes: require('./routes/v1/statements.routes.js'),
// //   stockRoutes: require('./routes/v1/stock.routes.js'),
// //   supplierRoutes: require('./routes/v1/supplier.routes.js'),
// //   transactionRoutes: require('./routes/v1/transaction.routes.js'),
// //   userRoutes: require('./routes/v1/user.routes.js'),

// //   // --- HRMS Routes ---
// //   attendanceDailyRoutes: require('./modules/HRMS/routes/attendance/attendanceDaily.routes.js'),
// //   attendanceLogRoutes: require('./modules/HRMS/routes/attendance/attendanceLog.routes.js'),
// //   attendanceMachineRoutes: require('./modules/HRMS/routes/attendance/attendanceMachine.routes.js'),
// //   geoFenceRoutes: require('./modules/HRMS/routes/attendance/geoFence.routes.js'),
// //   holidayRoutes: require('./modules/HRMS/routes/attendance/holiday.routes.js'),
// //   departmentRoutes: require('./modules/HRMS/routes/core/department.routes.js'),
// //   designationRoutes: require('./modules/HRMS/routes/core/designation.routes.js'),
// //   hrmsShiftGroupRoutes: require('./modules/HRMS/routes/core/shiftGroup.routes.js'),
// //   hrmsShiftRoutes: require('./modules/HRMS/routes/core/shift.routes.js'),
// //   leaveBalanceRoutes: require('./modules/HRMS/routes/leave/leaveBalance.routes.js'),
// //   leaveRequestRoutes: require('./modules/HRMS/routes/leave/leaveRequest.routes.js'),

// //   // --- Public Modules (Storefront) Routes ---
// //   storefrontAdminRoutes: require('./PublicModules/routes/storefront/admin.routes.js'),
// //   storefrontPublicRoutes: require('./PublicModules/routes/storefront/public.routes.js'),
// //   smartRuleRoutes: require('./PublicModules/routes/storefront/smartRule.routes.js'),
// // };