// src/config/swaggerConfig.js
const fs = require('fs');
const path = require('path');

let autoGeneratedPaths = {};
let autoGeneratedSchemas = {};
try {
  const swaggerFilePath = path.join(__dirname, '../../artifacts/swagger.json');
  if (fs.existsSync(swaggerFilePath)) {
    const rawData = fs.readFileSync(swaggerFilePath);
    const parsedData = JSON.parse(rawData);
    autoGeneratedPaths = parsedData.paths || {};
    autoGeneratedSchemas = parsedData.components?.schemas || {};
  }
} catch (error) {
  console.log('No auto-generated swagger.json found or failed to parse, falling back to empty paths.');
}

const swaggerSpec = {
  openapi: '3.0.0',
  info: {
    title: 'Apex CRM API',
    version: '1.0.0',
    description: 'Auto-extracted API documentation for the Apex Multi-Tenant, Multi-Branch CRM. Look at the bottom for Schemas and Models.',
    contact: {
      name: 'API Support',
      email: 'support@apex.com',
    },
  },
  servers: [
    {
      url: `http://localhost:${process.env.PORT || 5000}`,
      description: 'Development server (local)',
    },
  ],
  paths: autoGeneratedPaths,
  components: {
    schemas: autoGeneratedSchemas,
    securitySchemes: {
      bearerAuth: {
        type: 'http',
        scheme: 'bearer',
        bearerFormat: 'JWT',
        description: 'Enter your JWT token in the format: Bearer <token>',
      },
    },
  },
  // Apply Bearer auth globally by default
  security: [
    {
      bearerAuth: [],
    },
  ],
};

module.exports = swaggerSpec;